//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceKeeper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\JEXPRESS;AttachDbFilename=|DataDirectory|\\Data\\DTRDbase.mdf;Integra" +
            "ted Security=True;Connect Timeout=30;User Instance=True")]
        public string DTRDbaseConnectionString {
            get {
                return ((string)(this["DTRDbaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=coco-PC\\JExpress;Initial Catalog=DTRBase;Integrated Security=True")]
        public string DTRDbaseConnectionString2 {
            get {
                return ((string)(this["DTRDbaseConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\JEXPRESS;AttachDbFilename=C:\\Program Files\\247Solutions\\DTRSetup\\Da" +
            "ta\\DTRDbase.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True")]
        public string DTRDbaseConnectionString3 {
            get {
                return ((string)(this["DTRDbaseConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\JEXPRESS;AttachDbFilename=|DataDirectory|\\DTRDbase.mdf;Integrated S" +
            "ecurity=True;Connect Timeout=30;User Instance=True")]
        public string DTRDbaseConnectionString1 {
            get {
                return ((string)(this["DTRDbaseConnectionString1"]));
            }
        }
    }
}
